--- #YAML:1.0
name:               Filter-Unpound
version:            1
abstract:           Selective uncommenting for debugging.
author:
    - Mark E. Shoulson <mark@shoulson.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Filter::Simple:  0
    Test::More:      0
requires:
    Filter::Simple:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
